image:
  file: .gitpod.dockerfile

tasks:
  - init: pip install -r requirements.txt
  - command: |
      printf "\033[3J\033c\033[3J"
      printf '>>> %s\n' \
        "Please open the workspace in VS Code Desktop" \
        "See https://www.gitpod.io/docs/references/ides-and-editors/vscode for more info."

vscode:
  extensions:
    - ms-python.isort
    - ms-python.python
    - ms-toolsai.jupyter
    - formulahendry.auto-close-tag
    - eventyret.bootstrap-4-cdn-snippet
    - hookyqr.beautify
    - matt-rudge.auto-open-preview-panel
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers